version: '3'
services:
  arm-ripper:
    container_name: arm-ripper
    image: "automaticrippingmachine/automatic-ripping-machine:2.6.60"
    restart: unless-stopped
    ports:
      - "8001:8080"
    environment:
      - "ARM_UID=1000"
      - "ARM_GID=1000"
    privileged: true
    volumes:
      - "/mnt/docker-data/arm-ripper/home:/home/arm"
      - "/mnt/docker-data/arm-ripper/config:/etc/arm/config"
      - "/mnt/docker-data/arm-ripper/home/logs:/home/arm/logs"
      - "/mnt/docker-data/arm-ripper/home/Music:/home/arm/Music"
      - "/mnt/docker-data/arm-ripper/home/media:/home/arm/media"
    devices:
      - "/dev/sr0:/dev/sr0"
      - "/dev/sr1:/dev/sr1"
