version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    network_mode: 'host'
    volumes:
      - /mnt/docker-data/jellyfin/config:/config
      - /mnt/docker-data/jellyfin/cache:/cache
      - /mnt/media:/media
    restart: 'unless-stopped'
    environment:
      - JELLYFIN_PublishedServerUrl=http://files.home.nitori.org
    extra_hosts:
      - "host.docker.internal:host-gateway"
