#!/bin/bash

set -eux

PARENT_DISK="/dev/disk/by-id/usb-WD_easystore_264D_324A4A483759555A-0:0"
BASE_DISK="/dev/disk/by-id/usb-WD_easystore_264D_324A4A483759555A-0:0-part1"
CRYPT_LABEL="kiddie-pool-crypt"
ZFS_POOL="kiddie-pool"

cryptsetup luksOpen "$BASE_DISK" "$CRYPT_LABEL"
zpool import "$ZFS_POOL" -d /dev/disk/by-id
exit 1

# TODO: Find the latest local snapshot and latest remote snapshot. ZFS send the diff

zpool export "$ZFS_POOL"
cryptsetup luksClose "$CRYPT_LABEL"

udisksctl power-off -b "$PARENT_DISK"
