version: "3"
services:
  minecraft_server:
    container_name: minecraft_server
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    user: "1000:1000"
    volumes:
      - "/mnt/docker-data/minecraft:/data:rw"
    environment:
      - "EULA=TRUE"
      - "MEMORY=9G"
    tty: true
    stdin_open: true
    restart: unless-stopped
